services:
  db:
    image: postgres:18-alpine
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      # Esto permite que el usuario odoo tenga permisos de superusuario
      # necesarios para crear bases de datos desde el gestor de Odoo
      - POSTGRES_INITDB_ARGS=--auth-host=md5
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  odoo:
    image: localhost/odoo-pos:19.0
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - PGHOST=db
      - PGUSER=odoo
      - PGPASSWORD=odoo
      - ODOO_URL=http://localhost:8069
    volumes:
      - odoo-data:/var/lib/odoo
    restart: always

volumes:
  odoo-db-data:
  odoo-data:
